server: 
  port: 11001
 
eureka:
  instance:
    instance-id: zuul
    prefer-ip-address: true
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

spring:
  application:
    name: zuul

info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

zuul:
  prefix: /service
  #ignored-services: provider
  ignored-services: "*"
  routes:
    mydept.serviceId: provider
    mydept.path: /mydept/**