server: 
  port: 3344
  
spring:
  application:
    name:  config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/baifuhai/springcloud-config.git #GitHub上面的git仓库名字
 

